### ISSUE TITLE
Move to SemVer versioning system

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#13]
semver.org is a very sensible versioning system proposal to align projects and make it easier for the developer community to handle dependency management. Semver stands for Semantic Versioning and it is fairly simple at first glance consisting of a release description in format (x.y.z). Read more on their site or Github.

Goal: move to versioning system which will be communicated in Github, release notes on Discord and on the website itself.

This will be very important when the API wider usage as we add / deprecate / break functionality accordingly.

**Comment by f27d** [comment]
Started now. Closing.
