### ISSUE TITLE
Add dynamic mainnet JSON generator

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#17]
Currently, a lot of projects use the mainnet.json file (from City of Zion's monitor) which is a fixed list of addresses, locales and protocol/IP/port combinations.

Using our node discovery feature, we should be able to generate a dynamic mainnet json that automatically adds and removes nodes based on their status.

**Comment by wy** [comment]
This is based on #38. We probably want to keep offline nodes in there if we've ever seen them be active. Might need a cut-off to avoid the file getting too large with dead / decommissioned / invisible nodes.

**Comment by i25959341** [comment]
Fixed with #69
