### ISSUE TITLE
Live Client Side Latency is not working

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#18]
This was working on local, is this a CORS problem?

**Comment by wy** [comment]
This is linked to #8 - the typo means the address is not valid as an endpoint for the Client Side Latency check. Resolving one will fix the other.

**Comment by i25959341** [comment]
fixed #23

**Comment by wy** [comment]
Will close once released live and tested.

**Comment by wy** [comment]
Working - closed.
