### ISSUE TITLE
Document API using Swagger

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#19]
At the moment, the REST API can be understood quite easily through manual documentation since the number of methods is small. However, as the API develops it becomes more and more important to provide up-to-date documentation.

Swagger is a good solution to provide developers with contextualised documentation as well as providing an explorer interface.

**Comment by wy** [comment]
Added initial version here: https://app.swaggerhub.com/apis/F27/happynodes/1.0.0 - but will update this for 1.0 - FLASH.

**Comment by i25959341** [comment]
closed, need a better method
