### ISSUE TITLE
New API method - daily online

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#30]
Sample SQL code that works (needs refinement)

```
select ts, count(*) as online_nodes from
(
select address_id, ts::date, sum(case when online then 1 else 0 end)/(count(*)+0.0) as stability
FROM public.online_history
group by 1, 2
) daily
where stability > 0.9
group by 1
order by ts asc
```

Returns back the daily number of online nodes (defined if they were online for more than 90% of the observed time that day.
The 0.9 variable can be customised or even exposed in the API call but it should have a default value e.g. 0.9 seems reasonable. 100% is hard as there could be occasional failure due to server-server ping failure etc.

**Comment by i25959341** [comment]
Fixed with #69
