### ISSUE TITLE
Add Table View for advanced users

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#31]
City of Zion's monitor is arguably more useful for advanced users as all the information is in one table as opposed to having to click on each one.

This should be easy to do as 1.0 FLASH will mean super-fast response times anyway.

We probably need to update the API so all information is available in one place, i.e. by updates /nodes to include some of the extra information @i25959341 that is contained in /nodes/:id

**Comment by wy** [comment]
Fixed in https://github.com/neo-ngd/Happynodes/tree/v1.0.0

**Comment by i25959341** [comment]
fixed, but no PR
