### ISSUE TITLE
New API requests /nodes/all

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#32]
Returns all information needed for an extended version of CoZ's monitor #31 .

Fields needed (in order please):

1. id
2. address
3. protocol
4. version
5. blockheight
6. stability
7. latency
8. online
9. locale
10. territory
11. validated_peers
12. health_score
13. RPC (boolean)
14. RPC port
15. P2P (boolean)
16. P2P port
17. WS (boolean)
18. WS port

**Comment by wy** [comment]
https://github.com/neo-ngd/Happynodes/tree/v1.0.0

Changed to /nodes_flat

**Comment by i25959341** [comment]
No PR.
