### ISSUE TITLE
Add Node Discovery

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#38]
At the moment, Happynodes uses the mainnet.json file from neo-mon project and looks for valid JSON-RPC, P2P or WS connections. However, there are more nodes than the ones in that file.

Since we are running a node through our neo-node sub-project, we should be able to run node discovery and update the list of known addresses and connections.

**Comment by f27d** [comment]
Protocode:
- Start with list of known addresses
- Start a P2P node or use JSON-RPC to get IPs of other nodes
- Do Reverse lookup to get hostname from IP
- If hostname exists add it to address table (basically a ID->hostname mapping)
- If not hostname exists, add the IP address to the address table - that's the default hostname essentially

**Comment by i25959341** [comment]
fixed by #64 #63
