### ISSUE TITLE
Automatically pull latest mainnet.json from City of Zion

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#41]
Nodes often change or get added (and aren't always available via Public P2P, which means they can be challenging to find. Often, people update mainnet.json in City of Zion's neo-mon project, which makes perfect sense as it is the first and was the only monitoring solution.

Rather than duplicate work for teams, we should just allow the application to pull the latest (checking for changes) and then insert any new rows into the DB.

**Comment by f27d** [comment]
File should be stored here:
https://raw.githubusercontent.com/CityOfZion/neo-mon/master/docs/assets/mainnet.json

Try and pull from this link. If there is any problem, use the one in the directory instead.

**Comment by i25959341** [comment]
fixed by #64 #63
