### ISSUE TITLE
Add transaction explorer for unconfirmed transactions

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#44]
At the moment, the Unconfirmed TX list links back to Neo Tracker which doesn't make that much sense as a user experience, since the transaction isn't confirmed yet, so Neo Tracker doesn't show any details about it.

Instead, we can get more information about that transaction from the Nodes that have it in their rawmempool.

Using the API call: http://docs.neo.org/en-us/node/cli/2.7.6/api/getrawtransaction.html
You can use verbose to get out all the important details.

**Comment by i25959341** [comment]
fixed with #48

**Comment by i25959341** [comment]
Fixed with #78
