### ISSUE TITLE
Update table structure for Unique Node info

### ISSUE THREAD

**Issue by f27d** [neo-ngd/Happynodes#47]
It's a fairly safe assumption (although can be contravened) that a unique node is defined by a HOSTNAME and IP address. Connecting via HTTP/HTTPS, RPC/P2P/WS and different ports are all different connection possibilities but should be still talking to the same node.

Actually, in general, the IP address should be the unique identifier, but where possible we want to have a HOSTNAME too.

You can of course a deploy a server without creating a DNS entry. In which case, the HOSTNAME should just be the IP Address.

This will need refactoring in several areas.

**Comment by i25959341** [comment]
Fixed in Database, no PR
