### ISSUE TITLE
Add Redis to decouple API from Database

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#6]
HN 0.y.z versions all use a backend API (node.js x Express) with a direct Postgres connection to the database. Whilst we do have caching in place, some of the queries take 5,000ms+, and that means it is possible to cause problems with the database.

By adding Redis in between, and pushing updates to Redis and allowing the API to only read from Redis, we essentially control the load on the database, letting Redis do what it's designed to do - lightning fast reads.

This is the key change for Milestone 1.0 Flash.

**Comment by i25959341** [comment]
fixed with #46

**Comment by f27d** [comment]
Looking good, 7x speed improvement just on page load. Massive improvement in API on many different calls.
