### ISSUE TITLE
Typo character in API

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#8]
See https://github.com/neo-ngd/Happynodes/blob/da8d6d18ab8f6d6916a364fe363ddb4d533e07de/neo-back/routes/index.js#L495

There is a "Ï" character in the concat function. Please remove as unneeded.

**Comment by i25959341** [comment]
fixed #23

**Comment by wy** [comment]
Will re-open once released and tested on live.

**Comment by wy** [comment]
Working - closed.
