### ISSUE TITLE
Turn Unconfirmed TX on /ID page into a client-side call

### ISSUE THREAD

**Issue by wy** [neo-ngd/Happynodes#96]
### Current behavior
Current info on a node uses redis cache to get last unconfirmed count. Due to the time difference, by the time this information gets to redis and then back to the user, normally the mempool has updated.

### Expected behavior

Make this more 'live' by using a client-side call to do a JSON-RPC request (getmempool) and then simply count the number of TX. This only uses one RPC call, so it should be fairly light.

### How to reproduce

N/A

### Your environment

N/A

**Comment by wy** [comment]
@i25959341 maybe you have some ideas for this? I thought we could use axios on client side, turns out you were using ping for client-side latency

**Comment by i25959341** [comment]
I thought we were gonna cached it?

**Comment by i25959341** [comment]
It will be a lot faster if we update that figure directly into redis like blockheight

**Comment by i25959341** [comment]
update redis directly
fixed in  #105
